require('plugins')
require('keymappings')
require('settings')

-- Plugins
require('lsp-config')
require('compe-config')
require('lspsaga-config')
require('treesitter-config')
require('statusline')
require('gitsigns-config')
require('nvimtree-config')
require('kommentary-config')
require('dashboard-config')
require('bufferline-config')
